# permissions for end users to view mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: mykind-viewer-role
rules:
- apiGroups:
  - mygroup.pyhita.com
  resources:
  - mykinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.pyhita.com
  resources:
  - mykinds/status
  verbs:
  - get
